### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by GuilhermeGuimaraesDeMedeiros**
link at the shark image

### CODE REVIEW

**Comment by GuilhermeGuimaraesDeMedeiros** [comment]
[screenshot.pdf](https://github.com/flaviostutz/onboarding-web-students/files/14920513/screenshot.pdf)

**Review by flaviostutz — CHANGES_REQUESTED** [review]
Pls attach the screenshot of the running page on the PR description

**Comment by flaviostutz** [comment]
Paste the image as part of the PR description body, not as an attached PDF. It's more natural and easier to see :)

**Comment by GuilhermeGuimaraesDeMedeiros** [comment]
screenshot-1
screenshot-2

**Review by flaviostutz — APPROVED** [review]

**Pull request merged**
