### PR TITLE
bootstrap html3 page

### PR DESCRIPTION
**Pull request by nielsmijnster**

### CODE REVIEW

**Review by flaviostutz — APPROVED** [review]
Nice job!

**Comment by nielsmijnster** [comment]
i cannot change the description anymore. hereby then:
What?
Validation for the 4 fields in the form.
Why?
So all the user inputs are validated which needs to be done.

How?
Using the default form validation "required"

Screenshots:
Screenshot 2023-06-01 at 11 27 02

**Comment by flaviostutz** [comment]
Please send a screenshot showing a validation error.

**Comment by nielsmijnster** [comment]
image

**Pull request merged**
